"""добавление в  максимовсую конфигурацию до таблиы с файлами

Revision ID: 006d3742096f
Revises: 45a4abfe5ba8
Create Date: 2025-09-23 14:43:03.621427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006d3742096f'
down_revision: Union[str, None] = '45a4abfe5ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filemodel',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('aspect_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('violation_files',
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['file_hash'], ['filemodel.hash'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violationmodel.id'], ),
    sa.PrimaryKeyConstraint('violation_id', 'file_hash')
    )
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.drop_column('picture_hash')

    op.drop_table('violation_files')
    op.drop_table('filemodel')
    # ### end Alembic commands ###
