"""добавил поле number в violations

Revision ID: 206faf2ea97b
Revises: 0aa0b380f5e5
Create Date: 2026-01-12 11:08:56.228239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206faf2ea97b'
down_revision: Union[str, None] = '0aa0b380f5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True,  server_default="0"))


            # 2. заполнение
    op.execute("UPDATE violationmodel SET number = id")

            # 3. NOT NULL
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.alter_column(
            "number",
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
