"""удаление необходимости записывать картинку в базу

Revision ID: 523c798322a3
Revises: 006d3742096f
Create Date: 2025-09-29 09:18:17.952005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523c798322a3'
down_revision: Union[str, None] = '006d3742096f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
