"""убрал поля photo и photo_hash

Revision ID: 0aa0b380f5e5
Revises: 523c798322a3
Create Date: 2025-10-22 09:39:49.196985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa0b380f5e5'
down_revision: Union[str, None] = '523c798322a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.drop_column('picture_hash')
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('picture_hash', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
