"""добавил в нарушения поле с хэшем прикрепленной фотографии

Revision ID: 0b5cef9673cd
Revises: 45a4abfe5ba8
Create Date: 2025-08-22 11:26:11.997019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5cef9673cd'
down_revision: Union[str, None] = '45a4abfe5ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violationmodel', schema=None) as batch_op:
        batch_op.drop_column('picture_hash')

    # ### end Alembic commands ###
