"""responsible_text fiels

Revision ID: 886f60b7d0e3
Revises: 207e086b029a
Create Date: 2025-04-30 10:23:03.913183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886f60b7d0e3'
down_revision: Union[str, None] = '207e086b029a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areamodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_text', sa.String(length=250), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('responsible_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areamodel', schema=None) as batch_op:
        batch_op.alter_column('responsible_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('responsible_text')

    # ### end Alembic commands ###
