"""добавил две таблицы: файлы и их связь с нарушениями.

Revision ID: fb3bd500c7ff
Revises: 0b5cef9673cd
Create Date: 2025-08-22 15:49:15.072434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3bd500c7ff'
down_revision: Union[str, None] = '0b5cef9673cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filemodel',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('violation_files',
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['file_hash'], ['filemodel.hash'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violationmodel.id'], ),
    sa.PrimaryKeyConstraint('violation_id', 'file_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation_files')
    op.drop_table('filemodel')
    # ### end Alembic commands ###
